// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: ride/v1/ride.proto

package ridev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRideRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rider identifier.
	RiderId string `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	// Pickup latitude.
	PickupLat float64 `protobuf:"fixed64,2,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	// Pickup longitude.
	PickupLng float64 `protobuf:"fixed64,3,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	// Dropoff latitude.
	DropoffLat float64 `protobuf:"fixed64,4,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	// Dropoff longitude.
	DropoffLng float64 `protobuf:"fixed64,5,opt,name=dropoff_lng,json=dropoffLng,proto3" json:"dropoff_lng,omitempty"`
	// Idempotency key for retry-safe calls.
	IdempotencyKey string `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRideRequest) Reset() {
	*x = CreateRideRequest{}
	mi := &file_ride_v1_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequest) ProtoMessage() {}

func (x *CreateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequest.ProtoReflect.Descriptor instead.
func (*CreateRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRideRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *CreateRideRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *CreateRideRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *CreateRideRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *CreateRideRequest) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

func (x *CreateRideRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateRideRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateRideRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateRideResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Current ride status.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRideResponse) Reset() {
	*x = CreateRideResponse{}
	mi := &file_ride_v1_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideResponse) ProtoMessage() {}

func (x *CreateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideResponse.ProtoReflect.Descriptor instead.
func (*CreateRideResponse) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CreateRideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartMatchingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchingRequest) Reset() {
	*x = StartMatchingRequest{}
	mi := &file_ride_v1_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchingRequest) ProtoMessage() {}

func (x *StartMatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchingRequest.ProtoReflect.Descriptor instead.
func (*StartMatchingRequest) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{2}
}

func (x *StartMatchingRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *StartMatchingRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StartMatchingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StartMatchingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Current ride status.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchingResponse) Reset() {
	*x = StartMatchingResponse{}
	mi := &file_ride_v1_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchingResponse) ProtoMessage() {}

func (x *StartMatchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchingResponse.ProtoReflect.Descriptor instead.
func (*StartMatchingResponse) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{3}
}

func (x *StartMatchingResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *StartMatchingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AssignDriverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Offer identifier.
	OfferId string `protobuf:"bytes,3,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// Idempotency key for retry-safe calls.
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverRequest) Reset() {
	*x = AssignDriverRequest{}
	mi := &file_ride_v1_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverRequest) ProtoMessage() {}

func (x *AssignDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverRequest.ProtoReflect.Descriptor instead.
func (*AssignDriverRequest) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{4}
}

func (x *AssignDriverRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *AssignDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *AssignDriverRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *AssignDriverRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *AssignDriverRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AssignDriverRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AssignDriverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Current ride status.
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverResponse) Reset() {
	*x = AssignDriverResponse{}
	mi := &file_ride_v1_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverResponse) ProtoMessage() {}

func (x *AssignDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverResponse.ProtoReflect.Descriptor instead.
func (*AssignDriverResponse) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{5}
}

func (x *AssignDriverResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *AssignDriverResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *AssignDriverResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelRideRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Cancellation reason.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRideRequest) Reset() {
	*x = CancelRideRequest{}
	mi := &file_ride_v1_ride_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideRequest) ProtoMessage() {}

func (x *CancelRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideRequest.ProtoReflect.Descriptor instead.
func (*CancelRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CancelRideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelRideRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CancelRideRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CancelRideResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Current ride status.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRideResponse) Reset() {
	*x = CancelRideResponse{}
	mi := &file_ride_v1_ride_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideResponse) ProtoMessage() {}

func (x *CancelRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideResponse.ProtoReflect.Descriptor instead.
func (*CancelRideResponse) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CancelRideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateOfferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Offer TTL in seconds.
	OfferTtlSeconds int64 `protobuf:"varint,3,opt,name=offer_ttl_seconds,json=offerTtlSeconds,proto3" json:"offer_ttl_seconds,omitempty"`
	// Idempotency key for retry-safe calls.
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferRequest) Reset() {
	*x = CreateOfferRequest{}
	mi := &file_ride_v1_ride_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferRequest) ProtoMessage() {}

func (x *CreateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOfferRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CreateOfferRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreateOfferRequest) GetOfferTtlSeconds() int64 {
	if x != nil {
		return x.OfferTtlSeconds
	}
	return 0
}

func (x *CreateOfferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateOfferRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateOfferRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateOfferResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offer identifier.
	OfferId string `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// Ride identifier.
	RideId string `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Offer status.
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Offer expiry epoch seconds.
	ExpiresAt     int64 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferResponse) Reset() {
	*x = CreateOfferResponse{}
	mi := &file_ride_v1_ride_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferResponse) ProtoMessage() {}

func (x *CreateOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateOfferResponse) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOfferResponse) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *CreateOfferResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CreateOfferResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreateOfferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOfferResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type OfferActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offer identifier.
	OfferId string `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// Idempotency key for retry-safe calls.
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferActionRequest) Reset() {
	*x = OfferActionRequest{}
	mi := &file_ride_v1_ride_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferActionRequest) ProtoMessage() {}

func (x *OfferActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferActionRequest.ProtoReflect.Descriptor instead.
func (*OfferActionRequest) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{10}
}

func (x *OfferActionRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *OfferActionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *OfferActionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OfferActionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type OfferActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offer identifier.
	OfferId string `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// Ride identifier.
	RideId string `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Offer status.
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferActionResponse) Reset() {
	*x = OfferActionResponse{}
	mi := &file_ride_v1_ride_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferActionResponse) ProtoMessage() {}

func (x *OfferActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_v1_ride_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferActionResponse.ProtoReflect.Descriptor instead.
func (*OfferActionResponse) Descriptor() ([]byte, []int) {
	return file_ride_v1_ride_proto_rawDescGZIP(), []int{11}
}

func (x *OfferActionResponse) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *OfferActionResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *OfferActionResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *OfferActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_ride_v1_ride_proto protoreflect.FileDescriptor

const file_ride_v1_ride_proto_rawDesc = "" +
	"\n" +
	"\x12ride/v1/ride.proto\x12\aride.v1\"\x91\x02\n" +
	"\x11CreateRideRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x02 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x03 \x01(\x01R\tpickupLng\x12\x1f\n" +
	"\vdropoff_lat\x18\x04 \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lng\x18\x05 \x01(\x01R\n" +
	"dropoffLng\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\"E\n" +
	"\x12CreateRideResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"i\n" +
	"\x14StartMatchingRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"H\n" +
	"\x15StartMatchingResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc9\x01\n" +
	"\x13AssignDriverRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x19\n" +
	"\boffer_id\x18\x03 \x01(\tR\aofferId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"d\n" +
	"\x14AssignDriverResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"~\n" +
	"\x11CancelRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"E\n" +
	"\x12CancelRideResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xd9\x01\n" +
	"\x12CreateOfferRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12*\n" +
	"\x11offer_ttl_seconds\x18\x03 \x01(\x03R\x0fofferTtlSeconds\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"\x9d\x01\n" +
	"\x13CreateOfferResponse\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"\x92\x01\n" +
	"\x12OfferActionRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"~\n" +
	"\x13OfferActionResponse\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xe1\x04\n" +
	"\vRideService\x12E\n" +
	"\n" +
	"CreateRide\x12\x1a.ride.v1.CreateRideRequest\x1a\x1b.ride.v1.CreateRideResponse\x12N\n" +
	"\rStartMatching\x12\x1d.ride.v1.StartMatchingRequest\x1a\x1e.ride.v1.StartMatchingResponse\x12K\n" +
	"\fAssignDriver\x12\x1c.ride.v1.AssignDriverRequest\x1a\x1d.ride.v1.AssignDriverResponse\x12E\n" +
	"\n" +
	"CancelRide\x12\x1a.ride.v1.CancelRideRequest\x1a\x1b.ride.v1.CancelRideResponse\x12H\n" +
	"\vCreateOffer\x12\x1b.ride.v1.CreateOfferRequest\x1a\x1c.ride.v1.CreateOfferResponse\x12H\n" +
	"\vAcceptOffer\x12\x1b.ride.v1.OfferActionRequest\x1a\x1c.ride.v1.OfferActionResponse\x12I\n" +
	"\fDeclineOffer\x12\x1b.ride.v1.OfferActionRequest\x1a\x1c.ride.v1.OfferActionResponse\x12H\n" +
	"\vExpireOffer\x12\x1b.ride.v1.OfferActionRequest\x1a\x1c.ride.v1.OfferActionResponseB:Z8github.com/daffahilmyf/ride-hailing/proto/ride/v1;ridev1b\x06proto3"

var (
	file_ride_v1_ride_proto_rawDescOnce sync.Once
	file_ride_v1_ride_proto_rawDescData []byte
)

func file_ride_v1_ride_proto_rawDescGZIP() []byte {
	file_ride_v1_ride_proto_rawDescOnce.Do(func() {
		file_ride_v1_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ride_v1_ride_proto_rawDesc), len(file_ride_v1_ride_proto_rawDesc)))
	})
	return file_ride_v1_ride_proto_rawDescData
}

var file_ride_v1_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ride_v1_ride_proto_goTypes = []any{
	(*CreateRideRequest)(nil),     // 0: ride.v1.CreateRideRequest
	(*CreateRideResponse)(nil),    // 1: ride.v1.CreateRideResponse
	(*StartMatchingRequest)(nil),  // 2: ride.v1.StartMatchingRequest
	(*StartMatchingResponse)(nil), // 3: ride.v1.StartMatchingResponse
	(*AssignDriverRequest)(nil),   // 4: ride.v1.AssignDriverRequest
	(*AssignDriverResponse)(nil),  // 5: ride.v1.AssignDriverResponse
	(*CancelRideRequest)(nil),     // 6: ride.v1.CancelRideRequest
	(*CancelRideResponse)(nil),    // 7: ride.v1.CancelRideResponse
	(*CreateOfferRequest)(nil),    // 8: ride.v1.CreateOfferRequest
	(*CreateOfferResponse)(nil),   // 9: ride.v1.CreateOfferResponse
	(*OfferActionRequest)(nil),    // 10: ride.v1.OfferActionRequest
	(*OfferActionResponse)(nil),   // 11: ride.v1.OfferActionResponse
}
var file_ride_v1_ride_proto_depIdxs = []int32{
	0,  // 0: ride.v1.RideService.CreateRide:input_type -> ride.v1.CreateRideRequest
	2,  // 1: ride.v1.RideService.StartMatching:input_type -> ride.v1.StartMatchingRequest
	4,  // 2: ride.v1.RideService.AssignDriver:input_type -> ride.v1.AssignDriverRequest
	6,  // 3: ride.v1.RideService.CancelRide:input_type -> ride.v1.CancelRideRequest
	8,  // 4: ride.v1.RideService.CreateOffer:input_type -> ride.v1.CreateOfferRequest
	10, // 5: ride.v1.RideService.AcceptOffer:input_type -> ride.v1.OfferActionRequest
	10, // 6: ride.v1.RideService.DeclineOffer:input_type -> ride.v1.OfferActionRequest
	10, // 7: ride.v1.RideService.ExpireOffer:input_type -> ride.v1.OfferActionRequest
	1,  // 8: ride.v1.RideService.CreateRide:output_type -> ride.v1.CreateRideResponse
	3,  // 9: ride.v1.RideService.StartMatching:output_type -> ride.v1.StartMatchingResponse
	5,  // 10: ride.v1.RideService.AssignDriver:output_type -> ride.v1.AssignDriverResponse
	7,  // 11: ride.v1.RideService.CancelRide:output_type -> ride.v1.CancelRideResponse
	9,  // 12: ride.v1.RideService.CreateOffer:output_type -> ride.v1.CreateOfferResponse
	11, // 13: ride.v1.RideService.AcceptOffer:output_type -> ride.v1.OfferActionResponse
	11, // 14: ride.v1.RideService.DeclineOffer:output_type -> ride.v1.OfferActionResponse
	11, // 15: ride.v1.RideService.ExpireOffer:output_type -> ride.v1.OfferActionResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ride_v1_ride_proto_init() }
func file_ride_v1_ride_proto_init() {
	if File_ride_v1_ride_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ride_v1_ride_proto_rawDesc), len(file_ride_v1_ride_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ride_v1_ride_proto_goTypes,
		DependencyIndexes: file_ride_v1_ride_proto_depIdxs,
		MessageInfos:      file_ride_v1_ride_proto_msgTypes,
	}.Build()
	File_ride_v1_ride_proto = out.File
	file_ride_v1_ride_proto_goTypes = nil
	file_ride_v1_ride_proto_depIdxs = nil
}
