// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: ride/v1/ride.proto

package ridev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RideService_CreateRide_FullMethodName    = "/ride.v1.RideService/CreateRide"
	RideService_StartMatching_FullMethodName = "/ride.v1.RideService/StartMatching"
	RideService_AssignDriver_FullMethodName  = "/ride.v1.RideService/AssignDriver"
	RideService_CancelRide_FullMethodName    = "/ride.v1.RideService/CancelRide"
	RideService_CreateOffer_FullMethodName   = "/ride.v1.RideService/CreateOffer"
	RideService_AcceptOffer_FullMethodName   = "/ride.v1.RideService/AcceptOffer"
	RideService_DeclineOffer_FullMethodName  = "/ride.v1.RideService/DeclineOffer"
	RideService_ExpireOffer_FullMethodName   = "/ride.v1.RideService/ExpireOffer"
)

// RideServiceClient is the client API for RideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RideService defines ride lifecycle operations for internal use.
type RideServiceClient interface {
	// CreateRide creates a new ride request.
	CreateRide(ctx context.Context, in *CreateRideRequest, opts ...grpc.CallOption) (*CreateRideResponse, error)
	// StartMatching transitions a ride into matching state.
	StartMatching(ctx context.Context, in *StartMatchingRequest, opts ...grpc.CallOption) (*StartMatchingResponse, error)
	// AssignDriver assigns a driver to a ride.
	AssignDriver(ctx context.Context, in *AssignDriverRequest, opts ...grpc.CallOption) (*AssignDriverResponse, error)
	// CancelRide cancels a ride with a reason.
	CancelRide(ctx context.Context, in *CancelRideRequest, opts ...grpc.CallOption) (*CancelRideResponse, error)
	// CreateOffer creates a ride offer for a driver.
	CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*CreateOfferResponse, error)
	// AcceptOffer marks a pending offer as accepted.
	AcceptOffer(ctx context.Context, in *OfferActionRequest, opts ...grpc.CallOption) (*OfferActionResponse, error)
	// DeclineOffer marks a pending offer as declined.
	DeclineOffer(ctx context.Context, in *OfferActionRequest, opts ...grpc.CallOption) (*OfferActionResponse, error)
	// ExpireOffer marks a pending offer as expired.
	ExpireOffer(ctx context.Context, in *OfferActionRequest, opts ...grpc.CallOption) (*OfferActionResponse, error)
}

type rideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRideServiceClient(cc grpc.ClientConnInterface) RideServiceClient {
	return &rideServiceClient{cc}
}

func (c *rideServiceClient) CreateRide(ctx context.Context, in *CreateRideRequest, opts ...grpc.CallOption) (*CreateRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRideResponse)
	err := c.cc.Invoke(ctx, RideService_CreateRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) StartMatching(ctx context.Context, in *StartMatchingRequest, opts ...grpc.CallOption) (*StartMatchingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMatchingResponse)
	err := c.cc.Invoke(ctx, RideService_StartMatching_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) AssignDriver(ctx context.Context, in *AssignDriverRequest, opts ...grpc.CallOption) (*AssignDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignDriverResponse)
	err := c.cc.Invoke(ctx, RideService_AssignDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) CancelRide(ctx context.Context, in *CancelRideRequest, opts ...grpc.CallOption) (*CancelRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRideResponse)
	err := c.cc.Invoke(ctx, RideService_CancelRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*CreateOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOfferResponse)
	err := c.cc.Invoke(ctx, RideService_CreateOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) AcceptOffer(ctx context.Context, in *OfferActionRequest, opts ...grpc.CallOption) (*OfferActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferActionResponse)
	err := c.cc.Invoke(ctx, RideService_AcceptOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) DeclineOffer(ctx context.Context, in *OfferActionRequest, opts ...grpc.CallOption) (*OfferActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferActionResponse)
	err := c.cc.Invoke(ctx, RideService_DeclineOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) ExpireOffer(ctx context.Context, in *OfferActionRequest, opts ...grpc.CallOption) (*OfferActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferActionResponse)
	err := c.cc.Invoke(ctx, RideService_ExpireOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RideServiceServer is the server API for RideService service.
// All implementations must embed UnimplementedRideServiceServer
// for forward compatibility.
//
// RideService defines ride lifecycle operations for internal use.
type RideServiceServer interface {
	// CreateRide creates a new ride request.
	CreateRide(context.Context, *CreateRideRequest) (*CreateRideResponse, error)
	// StartMatching transitions a ride into matching state.
	StartMatching(context.Context, *StartMatchingRequest) (*StartMatchingResponse, error)
	// AssignDriver assigns a driver to a ride.
	AssignDriver(context.Context, *AssignDriverRequest) (*AssignDriverResponse, error)
	// CancelRide cancels a ride with a reason.
	CancelRide(context.Context, *CancelRideRequest) (*CancelRideResponse, error)
	// CreateOffer creates a ride offer for a driver.
	CreateOffer(context.Context, *CreateOfferRequest) (*CreateOfferResponse, error)
	// AcceptOffer marks a pending offer as accepted.
	AcceptOffer(context.Context, *OfferActionRequest) (*OfferActionResponse, error)
	// DeclineOffer marks a pending offer as declined.
	DeclineOffer(context.Context, *OfferActionRequest) (*OfferActionResponse, error)
	// ExpireOffer marks a pending offer as expired.
	ExpireOffer(context.Context, *OfferActionRequest) (*OfferActionResponse, error)
	mustEmbedUnimplementedRideServiceServer()
}

// UnimplementedRideServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRideServiceServer struct{}

func (UnimplementedRideServiceServer) CreateRide(context.Context, *CreateRideRequest) (*CreateRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRide not implemented")
}
func (UnimplementedRideServiceServer) StartMatching(context.Context, *StartMatchingRequest) (*StartMatchingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMatching not implemented")
}
func (UnimplementedRideServiceServer) AssignDriver(context.Context, *AssignDriverRequest) (*AssignDriverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignDriver not implemented")
}
func (UnimplementedRideServiceServer) CancelRide(context.Context, *CancelRideRequest) (*CancelRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRide not implemented")
}
func (UnimplementedRideServiceServer) CreateOffer(context.Context, *CreateOfferRequest) (*CreateOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOffer not implemented")
}
func (UnimplementedRideServiceServer) AcceptOffer(context.Context, *OfferActionRequest) (*OfferActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOffer not implemented")
}
func (UnimplementedRideServiceServer) DeclineOffer(context.Context, *OfferActionRequest) (*OfferActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclineOffer not implemented")
}
func (UnimplementedRideServiceServer) ExpireOffer(context.Context, *OfferActionRequest) (*OfferActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireOffer not implemented")
}
func (UnimplementedRideServiceServer) mustEmbedUnimplementedRideServiceServer() {}
func (UnimplementedRideServiceServer) testEmbeddedByValue()                     {}

// UnsafeRideServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RideServiceServer will
// result in compilation errors.
type UnsafeRideServiceServer interface {
	mustEmbedUnimplementedRideServiceServer()
}

func RegisterRideServiceServer(s grpc.ServiceRegistrar, srv RideServiceServer) {
	// If the following call pancis, it indicates UnimplementedRideServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RideService_ServiceDesc, srv)
}

func _RideService_CreateRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).CreateRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_CreateRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).CreateRide(ctx, req.(*CreateRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_StartMatching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMatchingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).StartMatching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_StartMatching_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).StartMatching(ctx, req.(*StartMatchingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_AssignDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).AssignDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_AssignDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).AssignDriver(ctx, req.(*AssignDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_CancelRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).CancelRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_CancelRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).CancelRide(ctx, req.(*CancelRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_CreateOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).CreateOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_CreateOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).CreateOffer(ctx, req.(*CreateOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_AcceptOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).AcceptOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_AcceptOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).AcceptOffer(ctx, req.(*OfferActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_DeclineOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).DeclineOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_DeclineOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).DeclineOffer(ctx, req.(*OfferActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_ExpireOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).ExpireOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_ExpireOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).ExpireOffer(ctx, req.(*OfferActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RideService_ServiceDesc is the grpc.ServiceDesc for RideService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RideService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ride.v1.RideService",
	HandlerType: (*RideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRide",
			Handler:    _RideService_CreateRide_Handler,
		},
		{
			MethodName: "StartMatching",
			Handler:    _RideService_StartMatching_Handler,
		},
		{
			MethodName: "AssignDriver",
			Handler:    _RideService_AssignDriver_Handler,
		},
		{
			MethodName: "CancelRide",
			Handler:    _RideService_CancelRide_Handler,
		},
		{
			MethodName: "CreateOffer",
			Handler:    _RideService_CreateOffer_Handler,
		},
		{
			MethodName: "AcceptOffer",
			Handler:    _RideService_AcceptOffer_Handler,
		},
		{
			MethodName: "DeclineOffer",
			Handler:    _RideService_DeclineOffer_Handler,
		},
		{
			MethodName: "ExpireOffer",
			Handler:    _RideService_ExpireOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ride/v1/ride.proto",
}
