// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: location/v1/location.proto

package locationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDriverLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverLocationRequest) Reset() {
	*x = GetDriverLocationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverLocationRequest) ProtoMessage() {}

func (x *GetDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*GetDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *GetDriverLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverLocationRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetDriverLocationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetDriverLocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Latitude.
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	// Longitude.
	Lng float64 `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	// Time recorded (unix seconds).
	RecordedAtUnix int64 `protobuf:"varint,4,opt,name=recorded_at_unix,json=recordedAtUnix,proto3" json:"recorded_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDriverLocationResponse) Reset() {
	*x = GetDriverLocationResponse{}
	mi := &file_location_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverLocationResponse) ProtoMessage() {}

func (x *GetDriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverLocationResponse.ProtoReflect.Descriptor instead.
func (*GetDriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriverLocationResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverLocationResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetDriverLocationResponse) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *GetDriverLocationResponse) GetRecordedAtUnix() int64 {
	if x != nil {
		return x.RecordedAtUnix
	}
	return 0
}

type UpdateDriverLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Latitude.
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	// Longitude.
	Lng float64 `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	// Accuracy in meters.
	AccuracyM float64 `protobuf:"fixed64,4,opt,name=accuracy_m,json=accuracyM,proto3" json:"accuracy_m,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRequest) Reset() {
	*x = UpdateDriverLocationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRequest) ProtoMessage() {}

func (x *UpdateDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDriverLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverLocationRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetAccuracyM() float64 {
	if x != nil {
		return x.AccuracyM
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *UpdateDriverLocationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UpdateDriverLocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result status.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationResponse) Reset() {
	*x = UpdateDriverLocationResponse{}
	mi := &file_location_v1_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationResponse) ProtoMessage() {}

func (x *UpdateDriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDriverLocationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_location_v1_location_proto protoreflect.FileDescriptor

const file_location_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x1alocation/v1/location.proto\x12\vlocation.v1\"q\n" +
	"\x18GetDriverLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\x86\x01\n" +
	"\x19GetDriverLocationResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12(\n" +
	"\x10recorded_at_unix\x18\x04 \x01(\x03R\x0erecordedAtUnix\"\xb7\x01\n" +
	"\x1bUpdateDriverLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12\x1d\n" +
	"\n" +
	"accuracy_m\x18\x04 \x01(\x01R\taccuracyM\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"6\n" +
	"\x1cUpdateDriverLocationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xe2\x01\n" +
	"\x0fLocationService\x12b\n" +
	"\x11GetDriverLocation\x12%.location.v1.GetDriverLocationRequest\x1a&.location.v1.GetDriverLocationResponse\x12k\n" +
	"\x14UpdateDriverLocation\x12(.location.v1.UpdateDriverLocationRequest\x1a).location.v1.UpdateDriverLocationResponseBBZ@github.com/daffahilmyf/ride-hailing/proto/location/v1;locationv1b\x06proto3"

var (
	file_location_v1_location_proto_rawDescOnce sync.Once
	file_location_v1_location_proto_rawDescData []byte
)

func file_location_v1_location_proto_rawDescGZIP() []byte {
	file_location_v1_location_proto_rawDescOnce.Do(func() {
		file_location_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)))
	})
	return file_location_v1_location_proto_rawDescData
}

var file_location_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_location_v1_location_proto_goTypes = []any{
	(*GetDriverLocationRequest)(nil),     // 0: location.v1.GetDriverLocationRequest
	(*GetDriverLocationResponse)(nil),    // 1: location.v1.GetDriverLocationResponse
	(*UpdateDriverLocationRequest)(nil),  // 2: location.v1.UpdateDriverLocationRequest
	(*UpdateDriverLocationResponse)(nil), // 3: location.v1.UpdateDriverLocationResponse
}
var file_location_v1_location_proto_depIdxs = []int32{
	0, // 0: location.v1.LocationService.GetDriverLocation:input_type -> location.v1.GetDriverLocationRequest
	2, // 1: location.v1.LocationService.UpdateDriverLocation:input_type -> location.v1.UpdateDriverLocationRequest
	1, // 2: location.v1.LocationService.GetDriverLocation:output_type -> location.v1.GetDriverLocationResponse
	3, // 3: location.v1.LocationService.UpdateDriverLocation:output_type -> location.v1.UpdateDriverLocationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_v1_location_proto_init() }
func file_location_v1_location_proto_init() {
	if File_location_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_v1_location_proto_goTypes,
		DependencyIndexes: file_location_v1_location_proto_depIdxs,
		MessageInfos:      file_location_v1_location_proto_msgTypes,
	}.Build()
	File_location_v1_location_proto = out.File
	file_location_v1_location_proto_goTypes = nil
	file_location_v1_location_proto_depIdxs = nil
}
