// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: matching/v1/matching.proto

package matchingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingService_FindCandidates_FullMethodName     = "/matching.v1.MatchingService/FindCandidates"
	MatchingService_NotifyOfferSent_FullMethodName    = "/matching.v1.MatchingService/NotifyOfferSent"
	MatchingService_UpdateDriverStatus_FullMethodName = "/matching.v1.MatchingService/UpdateDriverStatus"
)

// MatchingServiceClient is the client API for MatchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchingService provides driver candidate selection and offer notifications.
type MatchingServiceClient interface {
	// FindCandidates returns nearby available drivers.
	FindCandidates(ctx context.Context, in *FindCandidatesRequest, opts ...grpc.CallOption) (*FindCandidatesResponse, error)
	// NotifyOfferSent informs matching that an offer was sent.
	NotifyOfferSent(ctx context.Context, in *NotifyOfferSentRequest, opts ...grpc.CallOption) (*NotifyOfferSentResponse, error)
	// UpdateDriverStatus updates a driver's availability status.
	UpdateDriverStatus(ctx context.Context, in *UpdateDriverStatusRequest, opts ...grpc.CallOption) (*UpdateDriverStatusResponse, error)
}

type matchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingServiceClient(cc grpc.ClientConnInterface) MatchingServiceClient {
	return &matchingServiceClient{cc}
}

func (c *matchingServiceClient) FindCandidates(ctx context.Context, in *FindCandidatesRequest, opts ...grpc.CallOption) (*FindCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCandidatesResponse)
	err := c.cc.Invoke(ctx, MatchingService_FindCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) NotifyOfferSent(ctx context.Context, in *NotifyOfferSentRequest, opts ...grpc.CallOption) (*NotifyOfferSentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyOfferSentResponse)
	err := c.cc.Invoke(ctx, MatchingService_NotifyOfferSent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) UpdateDriverStatus(ctx context.Context, in *UpdateDriverStatusRequest, opts ...grpc.CallOption) (*UpdateDriverStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverStatusResponse)
	err := c.cc.Invoke(ctx, MatchingService_UpdateDriverStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingServiceServer is the server API for MatchingService service.
// All implementations must embed UnimplementedMatchingServiceServer
// for forward compatibility.
//
// MatchingService provides driver candidate selection and offer notifications.
type MatchingServiceServer interface {
	// FindCandidates returns nearby available drivers.
	FindCandidates(context.Context, *FindCandidatesRequest) (*FindCandidatesResponse, error)
	// NotifyOfferSent informs matching that an offer was sent.
	NotifyOfferSent(context.Context, *NotifyOfferSentRequest) (*NotifyOfferSentResponse, error)
	// UpdateDriverStatus updates a driver's availability status.
	UpdateDriverStatus(context.Context, *UpdateDriverStatusRequest) (*UpdateDriverStatusResponse, error)
	mustEmbedUnimplementedMatchingServiceServer()
}

// UnimplementedMatchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingServiceServer struct{}

func (UnimplementedMatchingServiceServer) FindCandidates(context.Context, *FindCandidatesRequest) (*FindCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCandidates not implemented")
}
func (UnimplementedMatchingServiceServer) NotifyOfferSent(context.Context, *NotifyOfferSentRequest) (*NotifyOfferSentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyOfferSent not implemented")
}
func (UnimplementedMatchingServiceServer) UpdateDriverStatus(context.Context, *UpdateDriverStatusRequest) (*UpdateDriverStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDriverStatus not implemented")
}
func (UnimplementedMatchingServiceServer) mustEmbedUnimplementedMatchingServiceServer() {}
func (UnimplementedMatchingServiceServer) testEmbeddedByValue()                         {}

// UnsafeMatchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingServiceServer will
// result in compilation errors.
type UnsafeMatchingServiceServer interface {
	mustEmbedUnimplementedMatchingServiceServer()
}

func RegisterMatchingServiceServer(s grpc.ServiceRegistrar, srv MatchingServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingService_ServiceDesc, srv)
}

func _MatchingService_FindCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).FindCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_FindCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).FindCandidates(ctx, req.(*FindCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_NotifyOfferSent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyOfferSentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).NotifyOfferSent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_NotifyOfferSent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).NotifyOfferSent(ctx, req.(*NotifyOfferSentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_UpdateDriverStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).UpdateDriverStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_UpdateDriverStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).UpdateDriverStatus(ctx, req.(*UpdateDriverStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingService_ServiceDesc is the grpc.ServiceDesc for MatchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching.v1.MatchingService",
	HandlerType: (*MatchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindCandidates",
			Handler:    _MatchingService_FindCandidates_Handler,
		},
		{
			MethodName: "NotifyOfferSent",
			Handler:    _MatchingService_NotifyOfferSent_Handler,
		},
		{
			MethodName: "UpdateDriverStatus",
			Handler:    _MatchingService_UpdateDriverStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matching/v1/matching.proto",
}
