// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: matching/v1/matching.proto

package matchingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindCandidatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Pickup latitude.
	PickupLat float64 `protobuf:"fixed64,2,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	// Pickup longitude.
	PickupLng float64 `protobuf:"fixed64,3,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	// Max number of candidates.
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCandidatesRequest) Reset() {
	*x = FindCandidatesRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCandidatesRequest) ProtoMessage() {}

func (x *FindCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCandidatesRequest.ProtoReflect.Descriptor instead.
func (*FindCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{0}
}

func (x *FindCandidatesRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *FindCandidatesRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *FindCandidatesRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *FindCandidatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindCandidatesRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *FindCandidatesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type FindCandidatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered list of candidates.
	Candidates    []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCandidatesResponse) Reset() {
	*x = FindCandidatesResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCandidatesResponse) ProtoMessage() {}

func (x *FindCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCandidatesResponse.ProtoReflect.Descriptor instead.
func (*FindCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{1}
}

func (x *FindCandidatesResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type Candidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Distance in meters.
	DistanceM     float64 `protobuf:"fixed64,2,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_matching_v1_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Candidate) GetDistanceM() float64 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

type NotifyOfferSentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ride identifier.
	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Offer identifier.
	OfferId string `protobuf:"bytes,3,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOfferSentRequest) Reset() {
	*x = NotifyOfferSentRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOfferSentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOfferSentRequest) ProtoMessage() {}

func (x *NotifyOfferSentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOfferSentRequest.ProtoReflect.Descriptor instead.
func (*NotifyOfferSentRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyOfferSentRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *NotifyOfferSentRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *NotifyOfferSentRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *NotifyOfferSentRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *NotifyOfferSentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type NotifyOfferSentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result status.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOfferSentResponse) Reset() {
	*x = NotifyOfferSentResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOfferSentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOfferSentResponse) ProtoMessage() {}

func (x *NotifyOfferSentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOfferSentResponse.ProtoReflect.Descriptor instead.
func (*NotifyOfferSentResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyOfferSentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateDriverStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Driver identifier.
	DriverId string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Driver status value.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Trace identifier for cross-service correlation.
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request identifier for idempotency/tracing.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverStatusRequest) Reset() {
	*x = UpdateDriverStatusRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverStatusRequest) ProtoMessage() {}

func (x *UpdateDriverStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverStatusRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDriverStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDriverStatusRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *UpdateDriverStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UpdateDriverStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result status.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverStatusResponse) Reset() {
	*x = UpdateDriverStatusResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverStatusResponse) ProtoMessage() {}

func (x *UpdateDriverStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverStatusResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDriverStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_matching_v1_matching_proto protoreflect.FileDescriptor

const file_matching_v1_matching_proto_rawDesc = "" +
	"\n" +
	"\x1amatching/v1/matching.proto\x12\vmatching.v1\"\xbe\x01\n" +
	"\x15FindCandidatesRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x02 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x03 \x01(\x01R\tpickupLng\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"P\n" +
	"\x16FindCandidatesResponse\x126\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x16.matching.v1.CandidateR\n" +
	"candidates\"G\n" +
	"\tCandidate\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"distance_m\x18\x02 \x01(\x01R\tdistanceM\"\xa3\x01\n" +
	"\x16NotifyOfferSentRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x19\n" +
	"\boffer_id\x18\x03 \x01(\tR\aofferId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"1\n" +
	"\x17NotifyOfferSentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x8a\x01\n" +
	"\x19UpdateDriverStatusRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"4\n" +
	"\x1aUpdateDriverStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb1\x02\n" +
	"\x0fMatchingService\x12Y\n" +
	"\x0eFindCandidates\x12\".matching.v1.FindCandidatesRequest\x1a#.matching.v1.FindCandidatesResponse\x12\\\n" +
	"\x0fNotifyOfferSent\x12#.matching.v1.NotifyOfferSentRequest\x1a$.matching.v1.NotifyOfferSentResponse\x12e\n" +
	"\x12UpdateDriverStatus\x12&.matching.v1.UpdateDriverStatusRequest\x1a'.matching.v1.UpdateDriverStatusResponseBBZ@github.com/daffahilmyf/ride-hailing/proto/matching/v1;matchingv1b\x06proto3"

var (
	file_matching_v1_matching_proto_rawDescOnce sync.Once
	file_matching_v1_matching_proto_rawDescData []byte
)

func file_matching_v1_matching_proto_rawDescGZIP() []byte {
	file_matching_v1_matching_proto_rawDescOnce.Do(func() {
		file_matching_v1_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_matching_proto_rawDesc), len(file_matching_v1_matching_proto_rawDesc)))
	})
	return file_matching_v1_matching_proto_rawDescData
}

var file_matching_v1_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_matching_v1_matching_proto_goTypes = []any{
	(*FindCandidatesRequest)(nil),      // 0: matching.v1.FindCandidatesRequest
	(*FindCandidatesResponse)(nil),     // 1: matching.v1.FindCandidatesResponse
	(*Candidate)(nil),                  // 2: matching.v1.Candidate
	(*NotifyOfferSentRequest)(nil),     // 3: matching.v1.NotifyOfferSentRequest
	(*NotifyOfferSentResponse)(nil),    // 4: matching.v1.NotifyOfferSentResponse
	(*UpdateDriverStatusRequest)(nil),  // 5: matching.v1.UpdateDriverStatusRequest
	(*UpdateDriverStatusResponse)(nil), // 6: matching.v1.UpdateDriverStatusResponse
}
var file_matching_v1_matching_proto_depIdxs = []int32{
	2, // 0: matching.v1.FindCandidatesResponse.candidates:type_name -> matching.v1.Candidate
	0, // 1: matching.v1.MatchingService.FindCandidates:input_type -> matching.v1.FindCandidatesRequest
	3, // 2: matching.v1.MatchingService.NotifyOfferSent:input_type -> matching.v1.NotifyOfferSentRequest
	5, // 3: matching.v1.MatchingService.UpdateDriverStatus:input_type -> matching.v1.UpdateDriverStatusRequest
	1, // 4: matching.v1.MatchingService.FindCandidates:output_type -> matching.v1.FindCandidatesResponse
	4, // 5: matching.v1.MatchingService.NotifyOfferSent:output_type -> matching.v1.NotifyOfferSentResponse
	6, // 6: matching.v1.MatchingService.UpdateDriverStatus:output_type -> matching.v1.UpdateDriverStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_matching_v1_matching_proto_init() }
func file_matching_v1_matching_proto_init() {
	if File_matching_v1_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_matching_proto_rawDesc), len(file_matching_v1_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_v1_matching_proto_goTypes,
		DependencyIndexes: file_matching_v1_matching_proto_depIdxs,
		MessageInfos:      file_matching_v1_matching_proto_msgTypes,
	}.Build()
	File_matching_v1_matching_proto = out.File
	file_matching_v1_matching_proto_goTypes = nil
	file_matching_v1_matching_proto_depIdxs = nil
}
